### ISSUE TITLE
CLI - Possibility to add parameters to a not final command

### ISSUE THREAD

**Issue by RegisGraptin** [HarvestersCrew/CorpusHarvester#38]
It's currently not possible to set a parameter for a command who have others command.
For example :
> harvester files list 
> harvester files --id "id"

It is not possible, because `files` have a subcommand `list` and raise an exception : 

> terminate called after throwing an instance of 'cli_parser_exception'
>   what():  Can't add an option as it already has commands

Code :
```
cli_command &filesCommand =
      this->parser.add_command("files", "Files function.");

  // Get a corpus based on his id
  filesCommand.add_option("id", "Id of a specific file.", false);

  // List of files
  cli_command &listFiles =
      filesCommand.add_command("list", "List of all the files.");
```

**Comment by ThibaultNocchi** [comment]
Both options and subcommands can be added to a command. On parsing, the first option found will declare the command terminal and will omit (or throw an exception) if it finds subcommands later.
