### ISSUE TITLE
API - Seach list of corpus - Name not defined 

### ISSUE THREAD

**Issue by RegisGraptin** [HarvestersCrew/CorpusHarvester#39]
Now, with the CLI, we have the possibility to search corpus based on his name and to put an ordering parameter. But we have an error, if the name is not precise and we want a specific ordering.

For example:
Here, I would like the list of all the corpuses, with an ascending ordering by the name.
`sudo ./bin/cli corpus list --order "name_asc" `
But, we have an error, more precisely an exception from the database :

> [DEBUG]   - Get all corpuses : 
> terminate called after throwing an instance of 'sql::SQLException'
>   what():  Unknown column 'name' in 'order clause'

However, if we precise the name, as:
` sudo ./bin/cli corpus list --order "name_asc" --name "lo"`
The request is executed without issue.

**Comment by ThibaultNocchi** [comment]
FIxed, it was because the DB uses the "title" attribute and not the "name" but the query ordered by "name".
