### ISSUE TITLE
Migrate setting storage path 

### ISSUE THREAD

**Issue by RegisGraptin** [HarvestersCrew/CorpusHarvester#44]
Now, with the CLI, we can modify the storage path with : 

> sudo ./bin/cli settings storage --migrate "my_new_path"

But, I have an error when I specified another path. I know that I need to fill in a folder that doesn't exist. Then, when I specified another, I got this error:

> sudo ./bin/cli settings storage --migrate "/tmp/doesnt_exist"

Error:

> terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
>   what():  filesystem error: cannot rename: Invalid cross-device link [/tmp/stored/] [/tmp/doesnt_exist/]

So, i don't know if I used this correctly ?

**Comment by ThibaultNocchi** [comment]
Yes, you must do a docker-compose build before retrying. Once the Dockerfile created the /tmp/stored directory and then there was a problem of permission or something. Now the executable creates the directory if necessary, so the permissions are better.
