### ISSUE TITLE
CLI - Add a type in the builder - Corpus creation

### ISSUE THREAD

**Issue by RegisGraptin** [HarvestersCrew/CorpusHarvester#48]
It seems that in function of the type parameter, we obtain huge difference in the database request.
Example :

Here, we precise the type parameter to obtain images :
> sudo ./bin/cli corpus create --name "Ananas" --number 20 --page 1 **--type image** --source Twitter --retweet 50 --op ">" --text "ananas" --source Flickr --title "ananas"

SQL response :
> [DEBUG]   - SELECT * FROM ((SELECT DISTINCT f.* FROM File f INNER JOIN Tag t ON f.id = t.file_id WHERE f.source = ? AND t.name = ? AND t.value = ?)) as result_table ORDER BY id LIMIT 20,20

Now, if we remove the type parameter, if we don't realize this code :
`builder.add_type(api_loader::api_type::IMAGE);`
And we realize this request :

> sudo ./bin/cli corpus create --name "Ananas" --number 20 --page 1 --source Twitter --retweet 50 --op ">" --text "ananas" --source Flickr --title "ananas"

We obtain :
> [DEBUG]   - SELECT * FROM ((SELECT DISTINCT f.* FROM File f INNER JOIN Tag t ON f.id = t.file_id WHERE f.source = ? AND t.name = ? AND t.value = ? INTERSECT SELECT DISTINCT f.* FROM File f INNER JOIN Tag t ON f.id = t.file_id WHERE f.source = ? AND t.name = ? AND CAST(t.value as INT) > CAST(? as INT)) UNION (SELECT DISTINCT f.* FROM File f INNER JOIN Tag t ON f.id = t.file_id WHERE f.source = ? AND t.name = ? AND t.value = ?)) as result_table ORDER BY id LIMIT 20,20

So, it seems that the type parameter removed other special parameter as retweet for the Twitter source or title from the Flickr source.

**Comment by ThibaultNocchi** [comment]
It is all working as intended. In the first query, only image sources will be used, so Twitter is omitted. In the second one, everything should also work as intended.
